### ISSUE TITLE
scalar bugs

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/VisualDL#199] opened 2018-01-22 14:54 UTC
![image](https://user-images.githubusercontent.com/328693/35226724-2b3080c8-ffc7-11e7-9b2d-743349c8a5ba.png)

一个是smooth算错了，另一个是排版问题
￼
遮挡曲线了

**Comment by ccmeteorljh** [comment] 2018-01-23 07:35
在画图的过程中，手动按F5刷新后，出现这样的情况
![image](https://user-images.githubusercontent.com/33303691/35263255-fe146924-0052-11e8-94d9-6645f4ff4854.png)

**Comment by ccmeteorljh** [comment] 2018-01-23 07:43
还有上下不同步的情况：
![1](https://user-images.githubusercontent.com/33303691/35263532-250c4e4c-0054-11e8-8688-1b64653b63cc.PNG)
![2](https://user-images.githubusercontent.com/33303691/35263538-2abdf5d4-0054-11e8-8005-de97350726ba.PNG)

**Comment by BingBlog** [comment] 2018-01-23 08:34
@ccmteorljh：
Thanks for the feedback. Problems you mentioned:
1、title display wrong (resolving);
2、smoothed error;
3、not synchronized;
4、refresh error;

About 2: I can't reproduce the scene you mentioned in the second problem, would you like to provide the callback data? Then I can check the smooth algorithm.

About 3 and 4: Does 3 and 4 appeared both after you refresh browser? The empty map may because the callback not return, and the browser does't get the data. It happens when the backend resolving the data.

**Comment by ZeyuChen** [comment] 2020-05-22 16:30
This issue was solved this issues in VisualDL 2.0-beta.

**Closed as completed by ZeyuChen** 2020-05-22 16:30 UTC
Labels: bug
