### ISSUE TITLE
PIP couldn't find a version that satisfies the requirement visualdl

### ISSUE THREAD

**Issue by fengziyue** [PaddlePaddle/VisualDL#217] opened 2018-01-26 07:24 UTC
fzyue@fzyue:~$ pip install --upgrade visualdl
Collecting visualdl
  Could not find a version that satisfies the requirement visualdl (from versions: )
No matching distribution found for visualdl

python 2.7.12
ubuntu 16.04 LTS

**Comment by AutuanLiu** [comment] 2018-01-26 13:54
```$ pip install --upgrade visualdl```
Collecting visualdl
  Could not find a version that satisfies the requirement visualdl (from versions: )
No matching distribution found for visualdl

* python 3.6.3
* ubuntu 16.04

**build and install locally also failed**

**Comment by jacquesqiao** [comment] 2018-01-29 07:56
please run
```
python -c "import pip; print(pip.pep425tags.get_supported())"
```
and paste the result.

**Comment by AutuanLiu** [comment] 2018-01-29 10:25
[('cp36', 'cp36m', 'manylinux1_x86_64'), ('cp36', 'cp36m', 'linux_x86_64'), ('cp36', 'abi3', 'manylinux1_x86_64'), ('cp36', 'abi3', 'linux_x86_64'), ('cp36', 'none', 'manylinux1_x86_64'), ('cp36', 'none', 'linux_x86_64'), ('cp35', 'abi3', 'manylinux1_x86_64'), ('cp35', 'abi3', 'linux_x86_64'), ('cp34', 'abi3', 'manylinux1_x86_64'), ('cp34', 'abi3', 'linux_x86_64'), ('cp33', 'abi3', 'manylinux1_x86_64'), ('cp33', 'abi3', 'linux_x86_64'), ('cp32', 'abi3', 'manylinux1_x86_64'), ('cp32', 'abi3', 'linux_x86_64'), ('py3', 'none', 'manylinux1_x86_64'), ('py3', 'none', 'linux_x86_64'), ('cp36', 'none', 'any'), ('cp3', 'none', 'any'), ('py36', 'none', 'any'), ('py3', 'none', 'any'), ('py35', 'none', 'any'), ('py34', 'none', 'any'), ('py33', 'none', 'any'), ('py32', 'none', 'any'), ('py31', 'none', 'any'), ('py30', 'none', 'any')]

**Comment by jacquesqiao** [comment] 2018-01-29 13:49
visualdl does not support Python3 now, please use it with Python2.7

**Comment by varunarora** [comment] 2018-02-02 20:16
Duplicate of #175. Closing.

**Closed as completed by varunarora** 2018-02-02 20:16 UTC

**Comment by harryprince** [comment] 2018-02-19 14:06
I am using py27, but the same issue.

Python 2.7.13
OS X El Capitan 10.11.5

I can search visualdl, however fail to install it by pip.

```
pip search visualdl
#visualdl (0.0.1a2)  - Visualize Deep Learning
```

```
python -c "import pip; print(pip.pep425tags.get_supported())"
```

result :

```
[('cp27', 'cp27m', 'macosx_10_11_x86_64'), ('cp27', 'cp27m', 'macosx_10_11_intel'), ('cp27', 'cp27m', 'macosx_10_11_fat64'), ('cp27', 'cp27m', 'macosx_10_11_fat32'), ('cp27', 'cp27m', 'macosx_10_11_universal'), ('cp27', 'cp27m', 'macosx_10_10_x86_64'), ('cp27', 'cp27m', 'macosx_10_10_intel'), ('cp27', 'cp27m', 'macosx_10_10_fat64'), ('cp27', 'cp27m', 'macosx_10_10_fat32'), ('cp27', 'cp27m', 'macosx_10_10_universal'), ('cp27', 'cp27m', 'macosx_10_9_x86_64'), ('cp27', 'cp27m', 'macosx_10_9_intel'), ('cp27', 'cp27m', 'macosx_10_9_fat64'), ('cp27', 'cp27m', 'macosx_10_9_fat32'), ('cp27', 'cp27m', 'macosx_10_9_universal'), ('cp27', 'cp27m', 'macosx_10_8_x86_64'), ('cp27', 'cp27m', 'macosx_10_8_intel'), ('cp27', 'cp27m', 'macosx_10_8_fat64'), ('cp27', 'cp27m', 'macosx_10_8_fat32'), ('cp27', 'cp27m', 'macosx_10_8_universal'), ('cp27', 'cp27m', 'macosx_10_7_x86_64'), ('cp27', 'cp27m', 'macosx_10_7_intel'), ('cp27', 'cp27m', 'macosx_10_7_fat64'), ('cp27', 'cp27m', 'macosx_10_7_fat32'), ('cp27', 'cp27m', 'macosx_10_7_universal'), ('cp27', 'cp27m', 'macosx_10_6_x86_64'), ('cp27', 'cp27m', 'macosx_10_6_intel'), ('cp27', 'cp27m', 'macosx_10_6_fat64'), ('cp27', 'cp27m', 'macosx_10_6_fat32'), ('cp27', 'cp27m', 'macosx_10_6_universal'), ('cp27', 'cp27m', 'macosx_10_5_x86_64'), ('cp27', 'cp27m', 'macosx_10_5_intel'), ('cp27', 'cp27m', 'macosx_10_5_fat64'), ('cp27', 'cp27m', 'macosx_10_5_fat32'), ('cp27', 'cp27m', 'macosx_10_5_universal'), ('cp27', 'cp27m', 'macosx_10_4_intel'), ('cp27', 'cp27m', 'macosx_10_4_fat32'), ('cp27', 'cp27m', 'macosx_10_4_universal'), ('cp27', 'cp27m', 'macosx_10_3_fat32'), ('cp27', 'cp27m', 'macosx_10_3_universal'), ('cp27', 'cp27m', 'macosx_10_2_fat32'), ('cp27', 'cp27m', 'macosx_10_2_universal'), ('cp27', 'cp27m', 'macosx_10_1_fat32'), ('cp27', 'cp27m', 'macosx_10_1_universal'), ('cp27', 'cp27m', 'macosx_10_0_fat32'), ('cp27', 'cp27m', 'macosx_10_0_universal'), ('cp27', 'none', 'macosx_10_11_x86_64'), ('cp27', 'none', 'macosx_10_11_intel'), ('cp27', 'none', 'macosx_10_11_fat64'), ('cp27', 'none', 'macosx_10_11_fat32'), ('cp27', 'none', 'macosx_10_11_universal'), ('cp27', 'none', 'macosx_10_10_x86_64'), ('cp27', 'none', 'macosx_10_10_intel'), ('cp27', 'none', 'macosx_10_10_fat64'), ('cp27', 'none', 'macosx_10_10_fat32'), ('cp27', 'none', 'macosx_10_10_universal'), ('cp27', 'none', 'macosx_10_9_x86_64'), ('cp27', 'none', 'macosx_10_9_intel'), ('cp27', 'none', 'macosx_10_9_fat64'), ('cp27', 'none', 'macosx_10_9_fat32'), ('cp27', 'none', 'macosx_10_9_universal'), ('cp27', 'none', 'macosx_10_8_x86_64'), ('cp27', 'none', 'macosx_10_8_intel'), ('cp27', 'none', 'macosx_10_8_fat64'), ('cp27', 'none', 'macosx_10_8_fat32'), ('cp27', 'none', 'macosx_10_8_universal'), ('cp27', 'none', 'macosx_10_7_x86_64'), ('cp27', 'none', 'macosx_10_7_intel'), ('cp27', 'none', 'macosx_10_7_fat64'), ('cp27', 'none', 'macosx_10_7_fat32'), ('cp27', 'none', 'macosx_10_7_universal'), ('cp27', 'none', 'macosx_10_6_x86_64'), ('cp27', 'none', 'macosx_10_6_intel'), ('cp27', 'none', 'macosx_10_6_fat64'), ('cp27', 'none', 'macosx_10_6_fat32'), ('cp27', 'none', 'macosx_10_6_universal'), ('cp27', 'none', 'macosx_10_5_x86_64'), ('cp27', 'none', 'macosx_10_5_intel'), ('cp27', 'none', 'macosx_10_5_fat64'), ('cp27', 'none', 'macosx_10_5_fat32'), ('cp27', 'none', 'macosx_10_5_universal'), ('cp27', 'none', 'macosx_10_4_intel'), ('cp27', 'none', 'macosx_10_4_fat32'), ('cp27', 'none', 'macosx_10_4_universal'), ('cp27', 'none', 'macosx_10_3_fat32'), ('cp27', 'none', 'macosx_10_3_universal'), ('cp27', 'none', 'macosx_10_2_fat32'), ('cp27', 'none', 'macosx_10_2_universal'), ('cp27', 'none', 'macosx_10_1_fat32'), ('cp27', 'none', 'macosx_10_1_universal'), ('cp27', 'none', 'macosx_10_0_fat32'), ('cp27', 'none', 'macosx_10_0_universal'), ('py2', 'none', 'macosx_10_11_x86_64'), ('py2', 'none', 'macosx_10_11_intel'), ('py2', 'none', 'macosx_10_11_fat64'), ('py2', 'none', 'macosx_10_11_fat32'), ('py2', 'none', 'macosx_10_11_universal'), ('py2', 'none', 'macosx_10_10_x86_64'), ('py2', 'none', 'macosx_10_10_intel'), ('py2', 'none', 'macosx_10_10_fat64'), ('py2', 'none', 'macosx_10_10_fat32'), ('py2', 'none', 'macosx_10_10_universal'), ('py2', 'none', 'macosx_10_9_x86_64'), ('py2', 'none', 'macosx_10_9_intel'), ('py2', 'none', 'macosx_10_9_fat64'), ('py2', 'none', 'macosx_10_9_fat32'), ('py2', 'none', 'macosx_10_9_universal'), ('py2', 'none', 'macosx_10_8_x86_64'), ('py2', 'none', 'macosx_10_8_intel'), ('py2', 'none', 'macosx_10_8_fat64'), ('py2', 'none', 'macosx_10_8_fat32'), ('py2', 'none', 'macosx_10_8_universal'), ('py2', 'none', 'macosx_10_7_x86_64'), ('py2', 'none', 'macosx_10_7_intel'), ('py2', 'none', 'macosx_10_7_fat64'), ('py2', 'none', 'macosx_10_7_fat32'), ('py2', 'none', 'macosx_10_7_universal'), ('py2', 'none', 'macosx_10_6_x86_64'), ('py2', 'none', 'macosx_10_6_intel'), ('py2', 'none', 'macosx_10_6_fat64'), ('py2', 'none', 'macosx_10_6_fat32'), ('py2', 'none', 'macosx_10_6_universal'), ('py2', 'none', 'macosx_10_5_x86_64'), ('py2', 'none', 'macosx_10_5_intel'), ('py2', 'none', 'macosx_10_5_fat64'), ('py2', 'none', 'macosx_10_5_fat32'), ('py2', 'none', 'macosx_10_5_universal'), ('py2', 'none', 'macosx_10_4_intel'), ('py2', 'none', 'macosx_10_4_fat32'), ('py2', 'none', 'macosx_10_4_universal'), ('py2', 'none', 'macosx_10_3_fat32'), ('py2', 'none', 'macosx_10_3_universal'), ('py2', 'none', 'macosx_10_2_fat32'), ('py2', 'none', 'macosx_10_2_universal'), ('py2', 'none', 'macosx_10_1_fat32'), ('py2', 'none', 'macosx_10_1_universal'), ('py2', 'none', 'macosx_10_0_fat32'), ('py2', 'none', 'macosx_10_0_universal'), ('cp27', 'none', 'any'), ('cp2', 'none', 'any'), ('py27', 'none', 'any'), ('py2', 'none', 'any'), ('py26', 'none', 'any'), ('py25', 'none', 'any'), ('py24', 'none', 'any'), ('py23', 'none', 'any'), ('py22', 'none', 'any'), ('py21', 'none', 'any'), ('py20', 'none', 'any')]
```

**Comment by cs2be** [comment] 2018-02-19 14:51
Hi Harry, currently we have packages for macOS 10.12 (Sierra) and above.  Please build the VisualDL from source if you need to run on El Capitan.  Thank you.

**Comment by FiReTiTi** [comment] 2018-11-13 00:36
Is Python 3 supported now?

**Comment by varunarora** [comment] 2018-11-20 06:16
@FiReTiTi I believe so, from https://github.com/PaddlePaddle/VisualDL/pull/314

**Comment by FiReTiTi** [comment] 2018-11-30 08:17
I still face the same error on Python 3:
Collecting visualdl
  Could not find a version that satisfies the requirement visualdl
