### ISSUE TITLE
Scalar graphs can't render both 0 records and very large # of records

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/VisualDL#203] opened 2018-01-24 06:43 UTC
- 0 records will result in a blank tablet, that's ok, but frontend will yield an error
- to0 many records(10000 for example) will make this scalar dead
   - TODO add reservoir sample in storage
   - TODO frontend should tolerate 0 records

**Comment by nickyfantasy** [comment] 2018-03-07 19:33
Empty records issue resolved in https://github.com/PaddlePaddle/VisualDL/pull/298

**Comment by ZeyuChen** [comment] 2020-06-15 06:26
We upgrade the sampling algorithm to avoid frontend dead caused by large amount scalar data.

**Closed as completed by ZeyuChen** 2020-06-15 06:26 UTC
Labels: bug, feature, suggestion
